# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 12:25
from __future__ import unicode_literals

import btdht_search.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btdht_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='token',
            field=models.CharField(default=btdht_search.utils.random_token, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
